import { Inter } from 'next/font/google'
import './globals.scss'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eatsy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} min-h-screen h-screen`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
