import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} min-h-screen h-screen`}>
        <header className='flex h-3/4 bg-green-300'>
          Header
        </header>
        {children}
      </body>
    </html>
  )
}
